"""
CQRS (Command Query Responsibility Segregation) for PyFault framework.
"""

from pyfault.common.cqrs.command import (
    Command,
    CommandHandler,
    CommandBus,
    CommandResult,
    CommandStatus,
    CreateEntityCommand,
    UpdateEntityCommand,
    DeleteEntityCommand,
    command,
)
from pyfault.common.cqrs.query import (
    Query,
    QueryHandler,
    QueryBus,
    QueryResult,
    QueryStatus,
    GetEntityQuery,
    ListEntitiesQuery,
    SearchEntitiesQuery,
    CountEntitiesQuery,
    QueryOptions,
    PaginatedQueryResult,
)
from pyfault.common.cqrs.dispatcher import MessageDispatcher
from pyfault.common.cqrs.middleware import (
    CommandMiddleware,
    QueryMiddleware,
    MiddlewareChain,
    LoggingMiddleware,
    ValidationMiddleware,
    RetryMiddleware,
    IdempotencyMiddleware,
    TransactionMiddleware,
    MiddlewareChainBuilder,
)
from pyfault.common.cqrs.decorators import (
    command_handler,
    query_handler,
    query,
    handles,
    validates,
    emits,
    requires,
    register_handler,
    get_handler_registry,
    create_command_handler,
    create_query_handler,
)

__all__ = [
    "Command",
    "CommandHandler",
    "CommandBus",
    "CommandResult",
    "CommandStatus",
    "CreateEntityCommand",
    "UpdateEntityCommand",
    "DeleteEntityCommand",
    "Query",
    "QueryHandler",
    "QueryBus",
    "QueryResult",
    "QueryStatus",
    "GetEntityQuery",
    "ListEntitiesQuery",
    "SearchEntitiesQuery",
    "CountEntitiesQuery",
    "QueryOptions",
    "PaginatedQueryResult",
    "MessageDispatcher",
    "CommandMiddleware",
    "QueryMiddleware",
    "MiddlewareChain",
    "LoggingMiddleware",
    "ValidationMiddleware",
    "RetryMiddleware",
    "IdempotencyMiddleware",
    "TransactionMiddleware",
    "MiddlewareChainBuilder",
    "command",
    "query",
    "handles",
    "validates",
    "emits",
    "requires",
    "register_handler",
    "get_handler_registry",
    "create_command_handler",
    "create_query_handler",
]