"""
AI Native Plugin System for PyFault.

This module provides AI-native capabilities including:
- Plugin marketplace for AI components
- Model inference integration
- Intelligent routing
- Adaptive autoscaling
- Model inference backends (ONNX, PyTorch, TensorFlow, etc.)
- Plugin sandbox isolation
- A/B testing framework
- Plugin dependency resolution
- Model versioning and canary deployment
"""

from .marketplace import (
    PluginManifest,
    PluginPackage,
    PluginStatus,
    PluginCategory,
    PluginRegistry,
    PluginInstaller,
    PluginManager,
    get_plugin_manager,
    set_plugin_manager,
)

from .inference import (
    ModelMetadata,
    ModelFormat,
    ModelStatus,
    InferenceRequest,
    InferenceResult,
    ModelBackend,
    ModelRegistry,
    ModelInstance,
    InferenceEngine,
    ModelServer,
    get_model_registry,
    get_inference_engine,
    get_model_server,
)

from .routing import (
    RouteTarget,
    RoutingContext,
    RoutingStrategy,
    IntelligentRouter,
    AIRouter,
)

from .autoscaling import (
    ScalingMetric,
    ScalingPolicy,
    ScalingAction,
    ScalingDirection,
    ScalingTrigger,
    MetricsCollector,
    ThresholdScalingStrategy,
    PredictiveScalingStrategy,
    AdaptiveScaler,
    ResourceScaler,
    get_adaptive_scaler,
    get_metrics_collector,
)

from .backends import (
    InferenceBackend,
    ONNXBackend,
    PyTorchBackend,
    TensorFlowBackend,
    SklearnBackend,
    XGBoostBackend,
    LightGBMBackend,
    CustomBackend,
    BackendConfig,
    create_backend,
    register_backend,
    get_available_backends,
)

from .sandbox import (
    SandboxType,
    SandboxConfig,
    SandboxResult,
    SandboxStats,
    Sandbox,
    NoSandbox,
    ProcessSandbox,
    ThreadSandbox,
    ContainerSandbox,
    WASMSandbox,
    SandboxManager,
    SecurityPolicy,
    DEFAULT_POLICIES,
    get_sandbox_manager,
)

from .abtesting import (
    ExperimentStatus,
    AssignmentStrategy,
    MetricType,
    ExperimentVariant,
    ExperimentMetric,
    Experiment,
    ExperimentAssignment,
    ExperimentEvent,
    ExperimentResult,
    AssignmentEngine,
    MetricCollector,
    StatisticalAnalyzer,
    ExperimentManager,
    ExperimentAutomation,
    create_simple_ab_test,
    create_multivariate_test,
    get_experiment_manager,
)

from .dependency import (
    DependencyType,
    VersionConstraint,
    VersionSpec,
    PluginDependency,
    PluginManifest,
    DependencyGraph,
    DependencyResolver,
    ResolutionResult,
    LockFileManager,
    ConflictResolver,
    VersionConflict,
    ResolutionOption,
    DependencyManager,
    get_dependency_manager,
)

from .versioning import (
    VersionStage,
    DeploymentStrategy,
    PromotionStatus,
    SemanticVersion,
    ModelVersion,
    DeploymentConfig,
    Deployment,
    PromotionRequest,
    CanaryMetrics,
    VersionRegistry,
    DeploymentManager,
    PromotionManager,
    RollbackManager,
    VersionManager,
    get_version_manager,
)

__all__ = [
    # Marketplace
    "PluginManifest",
    "PluginPackage",
    "PluginStatus",
    "PluginCategory",
    "PluginRegistry",
    "PluginInstaller",
    "PluginManager",
    "get_plugin_manager",
    "set_plugin_manager",
    # Inference
    "ModelMetadata",
    "ModelFormat",
    "ModelStatus",
    "InferenceRequest",
    "InferenceResult",
    "ModelBackend",
    "ModelRegistry",
    "ModelInstance",
    "InferenceEngine",
    "ModelServer",
    "get_model_registry",
    "get_inference_engine",
    "get_model_server",
    # Routing
    "RouteTarget",
    "RoutingContext",
    "RoutingStrategy",
    "IntelligentRouter",
    "AIRouter",
    # Autoscaling
    "ScalingMetric",
    "ScalingPolicy",
    "ScalingAction",
    "ScalingDirection",
    "ScalingTrigger",
    "MetricsCollector",
    "ThresholdScalingStrategy",
    "PredictiveScalingStrategy",
    "AdaptiveScaler",
    "ResourceScaler",
    "get_adaptive_scaler",
    "get_metrics_collector",
    # Backends
    "InferenceBackend",
    "ONNXBackend",
    "PyTorchBackend",
    "TensorFlowBackend",
    "SklearnBackend",
    "XGBoostBackend",
    "LightGBMBackend",
    "CustomBackend",
    "BackendConfig",
    "create_backend",
    "register_backend",
    "get_available_backends",
    # Sandbox
    "SandboxType",
    "SandboxConfig",
    "SandboxResult",
    "SandboxStats",
    "Sandbox",
    "NoSandbox",
    "ProcessSandbox",
    "ThreadSandbox",
    "ContainerSandbox",
    "WASMSandbox",
    "SandboxManager",
    "SecurityPolicy",
    "DEFAULT_POLICIES",
    "get_sandbox_manager",
    # A/B Testing
    "ExperimentStatus",
    "AssignmentStrategy",
    "MetricType",
    "ExperimentVariant",
    "ExperimentMetric",
    "Experiment",
    "ExperimentAssignment",
    "ExperimentEvent",
    "ExperimentResult",
    "AssignmentEngine",
    "MetricCollector",
    "StatisticalAnalyzer",
    "ExperimentManager",
    "ExperimentAutomation",
    "create_simple_ab_test",
    "create_multivariate_test",
    "get_experiment_manager",
    # Dependency
    "DependencyType",
    "VersionConstraint",
    "VersionSpec",
    "PluginDependency",
    "PluginManifest",
    "DependencyGraph",
    "DependencyResolver",
    "ResolutionResult",
    "LockFileManager",
    "ConflictResolver",
    "VersionConflict",
    "ResolutionOption",
    "DependencyManager",
    "get_dependency_manager",
    # Versioning
    "VersionStage",
    "DeploymentStrategy",
    "PromotionStatus",
    "SemanticVersion",
    "ModelVersion",
    "DeploymentConfig",
    "Deployment",
    "PromotionRequest",
    "CanaryMetrics",
    "VersionRegistry",
    "DeploymentManager",
    "PromotionManager",
    "RollbackManager",
    "VersionManager",
    "get_version_manager",
]