"""
Enterprise Module for PyFault framework.

Provides enterprise-grade features:
- Multi-tenant management with isolation
- Authentication & Authorization (RBAC, OAuth2, MFA)
- Audit logging and compliance
- Cost tracking and optimization
- Compliance framework management
"""

from .audit import (
    AuditEvent,
    AuditEventType,
    AuditLogger,
    AuditOutcome,
    AuditQueryBuilder,
    AuditSeverity,
    AuditStore,
    ComplianceReporter,
    get_audit_logger,
    init_audit_logger,
)
from .auth import (
    APIKey,
    AuthManager,
    AuthProvider,
    MFAManager,
    PasswordManager,
    Permission,
    PermissionSet,
    Role,
    RoleRegistry,
    RoleType,
    Session,
    TokenManager,
    TokenType,
    User,
    get_auth_manager,
    init_auth_manager,
)
from .auth import (
    Tenant as AuthTenant,
)
from .compliance import (
    AutomatedComplianceChecker,
    ComplianceAssessment,
    ComplianceDashboard,
    ComplianceFramework,
    ComplianceManager,
    ControlImplementation,
    ControlStatus,
    Evidence,
    EvidenceType,
    FrameworkControl,
    FrameworkRegistry,
    Policy,
    PolicyStatus,
    Risk,
    RiskLevel,
    TestResult,
    get_compliance_manager,
)
from .cost import (
    BillingPeriod,
    Budget,
    CostAllocation,
    CostCategory,
    CostOptimizationRecommendation,
    CostOptimizer,
    CostReporter,
    CostTracker,
    Currency,
    PriceRule,
    ResourceType,
    UsageRecord,
    get_cost_optimizer,
    get_cost_reporter,
    get_cost_tracker,
)
from .tenant import (
    IsolationLevel,
    ResourceQuota,
    ResourceQuotaType,
    Tenant,
    TenantAwareService,
    TenantContext,
    TenantInvitation,
    TenantManager,
    TenantMiddleware,
    TenantPlan,
    TenantStatus,
    get_tenant_context,
    get_tenant_manager,
)

__all__ = [
    # Auth
    "AuthProvider",
    "TokenType",
    "Permission",
    "RoleType",
    "PermissionSet",
    "Role",
    "AuthTenant",
    "User",
    "Session",
    "APIKey",
    "TokenManager",
    "PasswordManager",
    "MFAManager",
    "RoleRegistry",
    "AuthManager",
    "get_auth_manager",
    "init_auth_manager",
    # Audit
    "AuditEventType",
    "AuditSeverity",
    "AuditOutcome",
    "AuditEvent",
    "AuditStore",
    "AuditLogger",
    "AuditQueryBuilder",
    "ComplianceReporter",
    "get_audit_logger",
    "init_audit_logger",
    # Cost
    "ResourceType",
    "CostCategory",
    "BillingPeriod",
    "Currency",
    "PriceRule",
    "UsageRecord",
    "Budget",
    "CostAllocation",
    "CostOptimizationRecommendation",
    "CostTracker",
    "CostReporter",
    "CostOptimizer",
    "get_cost_tracker",
    "get_cost_reporter",
    "get_cost_optimizer",
    # Compliance
    "ComplianceFramework",
    "ControlStatus",
    "EvidenceType",
    "RiskLevel",
    "PolicyStatus",
    "FrameworkControl",
    "ControlImplementation",
    "Evidence",
    "TestResult",
    "Policy",
    "Risk",
    "ComplianceAssessment",
    "FrameworkRegistry",
    "ComplianceManager",
    "ComplianceDashboard",
    "AutomatedComplianceChecker",
    "get_compliance_manager",
    # Tenant
    "TenantStatus",
    "TenantPlan",
    "ResourceQuotaType",
    "IsolationLevel",
    "ResourceQuota",
    "Tenant",
    "TenantInvitation",
    "TenantManager",
    "TenantContext",
    "TenantAwareService",
    "TenantMiddleware",
    "get_tenant_manager",
    "get_tenant_context",
]
